language: go

go:
  - "1.12"

env:
  - RACE=-race
  - RACE=

before_install:
  - sudo cat /etc/issue
  - sudo cat /etc/lsb-release
  - sudo apt-get purge runit
  - sudo apt-get autoremove
  - sudo apt-get update -qq
  - sudo apt-get install -y runit runit-systemd

install:
  - gem install rake
  - go get github.com/kisielk/errcheck
  - rake install
  - wget https://releases.hashicorp.com/consul/0.9.4/consul_0.9.4_linux_amd64.zip
  - unzip consul_0.9.4_linux_amd64.zip
  - sudo mv consul /usr/bin/

script:
  - rake test_all
  - integration/travis.sh
  - rake errcheck
  - go vet ./bin/... ./pkg/...

sudo: required
services:
  - docker
